// <auto-generated />
using System;
using EnquiryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnquiryManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ContactPersonEnquiry", b =>
                {
                    b.Property<int>("EnquiriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedReceivedFromsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnquiriesId", "SelectedReceivedFromsId");

                    b.HasIndex("SelectedReceivedFromsId");

                    b.ToTable("ContactPersonEnquiry");
                });

            modelBuilder.Entity("CustomerCompanyEnquiry", b =>
                {
                    b.Property<int>("EnquiriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedCustomersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnquiriesId", "SelectedCustomersId");

                    b.HasIndex("SelectedCustomersId");

                    b.ToTable("CustomerCompanyEnquiry");
                });

            modelBuilder.Entity("EnquiryContactPerson", b =>
                {
                    b.Property<int>("EnquiriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedReceivedFromsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnquiriesId", "SelectedReceivedFromsId");

                    b.ToTable("EnquiryContactPerson");

                    b.HasData(
                        new
                        {
                            EnquiriesId = 1,
                            SelectedReceivedFromsId = 3
                        });
                });

            modelBuilder.Entity("EnquiryCustomerCompany", b =>
                {
                    b.Property<int>("EnquiriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedCustomersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnquiriesId", "SelectedCustomersId");

                    b.ToTable("EnquiryCustomerCompany");

                    b.HasData(
                        new
                        {
                            EnquiriesId = 1,
                            SelectedCustomersId = 1
                        });
                });

            modelBuilder.Entity("EnquiryEnquiryForItem", b =>
                {
                    b.Property<int>("EnquiriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedEnquiryForId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnquiriesId", "SelectedEnquiryForId");

                    b.HasIndex("SelectedEnquiryForId");

                    b.ToTable("EnquiryEnquiryForItem");

                    b.HasData(
                        new
                        {
                            EnquiriesId = 1,
                            SelectedEnquiryForId = 1
                        });
                });

            modelBuilder.Entity("EnquiryManagementSystem.Data.Models.ContactPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryOfDesignation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaxNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCompanyId");

                    b.ToTable("ContactPersons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "123 Main St",
                            CategoryOfDesignation = "Technical",
                            ContactName = "Velu",
                            CustomerCompanyId = 1,
                            Designation = "Manager",
                            EmailId = "pa@custx.com",
                            Mobile1 = "333"
                        },
                        new
                        {
                            Id = 2,
                            Address1 = "456 Oak Ave",
                            CategoryOfDesignation = "Technical",
                            ContactName = "Vijay",
                            CustomerCompanyId = 2,
                            Designation = "Director",
                            EmailId = "pb@custy.com",
                            Mobile1 = "666"
                        },
                        new
                        {
                            Id = 3,
                            Address1 = "123 Main St",
                            CategoryOfDesignation = "Technical",
                            ContactName = "Seema",
                            CustomerCompanyId = 1,
                            Designation = "Engineer",
                            EmailId = "sc@custx.com",
                            Mobile1 = "333"
                        },
                        new
                        {
                            Id = 4,
                            Address1 = "789 Pine Rd",
                            CategoryOfDesignation = "Technical",
                            ContactName = "Person C - Engineer",
                            CustomerCompanyId = 3,
                            Designation = "Engineer",
                            EmailId = "pc@clientz.com",
                            Mobile1 = "999"
                        });
                });

            modelBuilder.Entity("EnquiryManagementSystem.Data.Models.CustomerCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaxNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomerCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "123 Main St",
                            Category = "Contractor",
                            CompanyName = "Customer X Ltd",
                            Phone1 = "222",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Address1 = "456 Oak Ave",
                            Category = "Contractor",
                            CompanyName = "Customer Y Corp",
                            Phone1 = "555",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Address1 = "789 Pine Rd",
                            Category = "Client",
                            CompanyName = "Client Z Inc",
                            Phone1 = "888",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Address1 = "101 Elm Blvd",
                            Category = "Consultant",
                            CompanyName = "Consultant A",
                            Phone1 = "000",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EnquiryManagementSystem.Data.Models.Enquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoAck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsultantName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsOfEnquiry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentsReceived")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnquiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedEnquiryTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SiteVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOfInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ceosign")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("drawing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("dvd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("eqpschedule")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("hardcopy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("spec")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Enquiries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoAck = false,
                            ClientName = "Client Z Inc",
                            ConsultantName = "Consultant A",
                            DetailsOfEnquiry = "Initial seeded enquiry",
                            DocumentsReceived = "",
                            DueOn = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnquiryDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectName = "Project Alpha",
                            Remark = "",
                            RequestNo = "EYS/2025/11/001",
                            SelectedEnquiryTypes = "Re-Tender",
                            SourceOfInfo = "Phone",
                            Status = "Enquiry",
                            ceosign = false,
                            drawing = true,
                            dvd = false,
                            eqpschedule = false,
                            hardcopy = true,
                            spec = false
                        });
                });

            modelBuilder.Entity("EnquiryManagementSystem.Data.Models.EnquiryForItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCMailIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonMailIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EnquiryForItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CCMailIds = "",
                            CommonMailIds = "elect_common@a.com",
                            DepartmentName = "Elect",
                            ItemName = "Electrical",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CCMailIds = "mech_cc1@b.com",
                            CommonMailIds = "",
                            DepartmentName = "Mech",
                            ItemName = "Mechanical",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EnquiryManagementSystem.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "MEP",
                            Designation = "Sales Engineer",
                            FullName = "SE1 - John Doe",
                            LoginPassword = "123",
                            MailId = "se1@comp.com",
                            Roles = "Enquiry,Quotation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Department = "MEP",
                            Designation = "Sales Manager",
                            FullName = "SE2 - Jane Smith",
                            LoginPassword = "123",
                            MailId = "se2@comp.com",
                            Roles = "Enquiry,Admin",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EnquiryUser", b =>
                {
                    b.Property<int>("EnquiriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedConcernedSEsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnquiriesId", "SelectedConcernedSEsId");

                    b.HasIndex("SelectedConcernedSEsId");

                    b.ToTable("EnquiryUser");

                    b.HasData(
                        new
                        {
                            EnquiriesId = 1,
                            SelectedConcernedSEsId = 2
                        });
                });

            modelBuilder.Entity("ContactPersonEnquiry", b =>
                {
                    b.HasOne("EnquiryManagementSystem.Data.Models.Enquiry", null)
                        .WithMany()
                        .HasForeignKey("EnquiriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnquiryManagementSystem.Data.Models.ContactPerson", null)
                        .WithMany()
                        .HasForeignKey("SelectedReceivedFromsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerCompanyEnquiry", b =>
                {
                    b.HasOne("EnquiryManagementSystem.Data.Models.Enquiry", null)
                        .WithMany()
                        .HasForeignKey("EnquiriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnquiryManagementSystem.Data.Models.CustomerCompany", null)
                        .WithMany()
                        .HasForeignKey("SelectedCustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnquiryEnquiryForItem", b =>
                {
                    b.HasOne("EnquiryManagementSystem.Data.Models.Enquiry", null)
                        .WithMany()
                        .HasForeignKey("EnquiriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnquiryManagementSystem.Data.Models.EnquiryForItem", null)
                        .WithMany()
                        .HasForeignKey("SelectedEnquiryForId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnquiryManagementSystem.Data.Models.ContactPerson", b =>
                {
                    b.HasOne("EnquiryManagementSystem.Data.Models.CustomerCompany", "CustomerCompany")
                        .WithMany("ContactPersons")
                        .HasForeignKey("CustomerCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerCompany");
                });

            modelBuilder.Entity("EnquiryUser", b =>
                {
                    b.HasOne("EnquiryManagementSystem.Data.Models.Enquiry", null)
                        .WithMany()
                        .HasForeignKey("EnquiriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnquiryManagementSystem.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SelectedConcernedSEsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnquiryManagementSystem.Data.Models.CustomerCompany", b =>
                {
                    b.Navigation("ContactPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
